import { config as baseConfig } from '@repo/eslint-config/base';

/**
 * @type {import("eslint").Linter.Config[]}
 */
export default [
  ...baseConfig,
  {
    ignores: ['android/**', 'ios/**', 'board/**', '.expo/**'],
  },
  {
    rules: {
      // React Native and external libraries
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/init-declarations': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/promise-function-async': 'off',
      '@typescript-eslint/class-methods-use-this': 'off',
      '@typescript-eslint/prefer-destructuring': 'off',
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/no-extraneous-class': 'off',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/prefer-readonly': 'off',
      '@typescript-eslint/no-duplicate-type-constituents': 'off',
      '@typescript-eslint/no-import-type-side-effects': 'off',
      '@typescript-eslint/no-loop-func': 'off',
      '@typescript-eslint/no-throw-literal': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/max-params': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/no-meaningless-void-operator': 'off',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
      'turbo/no-undeclared-env-vars': 'off',
      'consistent-return': 'off',
      'no-empty': 'off',
      'no-empty-function': 'off',
      'no-param-reassign': 'off',
      'prefer-const': 'off',
      'func-style': 'off',
      'no-else-return': 'off',
      'no-void': 'off',
      'prefer-destructuring': 'off',
      'arrow-body-style': 'off',
      'default-case': 'off',
      'no-nested-ternary': 'off',
      'no-implicit-coercion': 'off',
      'eqeqeq': 'off',
      'no-undef': 'off',
      'no-use-before-define': 'off',
      'max-params': 'off',
      // React rules
      'react/no-multi-comp': 'off',
      'react/prop-types': 'off',
      'react/jsx-handler-names': 'off',
      'react/no-array-index-key': 'off',
      'react/no-unstable-nested-components': 'off',
      'react/no-unused-prop-types': 'off',
      'react/no-unused-state': 'off',
      'react/destructuring-assignment': 'off',
      'react/function-component-definition': 'off',
      'react/button-has-type': 'off',
      'react/no-unescaped-entities': 'off',
      'react/self-closing-comp': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react-hooks/rules-of-hooks': 'off',
    },
  },
];
