import { existsSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import dotenv from 'dotenv';

const ROOT = path.resolve(import.meta.dir, '..');
const ENV_DIR = path.join(ROOT, 'apps/docker/env');
const ROOT_ENV = path.join(ROOT, '.env');

if (!existsSync(ROOT_ENV)) {
  console.error('Root .env not found at', ROOT_ENV);
  process.exit(1);
}

const parsed = dotenv.parse(
  await Bun.file(ROOT_ENV).text(),
);

function requireKey(key: string): string {
  const value = parsed[key]?.trim();
  if (!value) {
    console.error(`Missing required key in root .env: ${key}`);
    process.exit(1);
  }
  return value.replace(/^['"]|['"]$/g, '');
}

function toDockerDatabaseUrl(url: string): string {
  return url
    .replace(/@localhost:5434\b/, '@postgres:5432')
    .replace(/@127\.0\.0\.1:5434\b/, '@postgres:5432');
}

function toDockerRedisUrl(url: string): string {
  return url
    .replace(/\/\/localhost:6379\b/, '//redis:6379')
    .replace(/\/\/127\.0\.0\.1:6379\b/, '//redis:6379');
}

function toDockerMongoUrl(url: string): string {
  return url
    .replace(/^['"]|['"]$/g, '')
    .replace(/@localhost:27017\b/, '@mongodb:27017')
    .replace(/@127\.0\.0\.1:27017\b/, '@mongodb:27017');
}

const DOCKER_BACKEND_URL = 'http://localhost:8000';
const DOCKER_FRONTEND_URL = parsed.FRONTEND_URL?.trim() || 'http://localhost:3001';

const shared = {
  DATABASE_URL: toDockerDatabaseUrl(requireKey('DATABASE_URL')),
  REDIS_URL: toDockerRedisUrl(requireKey('REDIS_URL')),
  MONGODB_URL: toDockerMongoUrl(requireKey('MONGODB_URL')),
  FRONTEND_URL: DOCKER_FRONTEND_URL,
  BACKEND_URL: DOCKER_BACKEND_URL,
  JWT_SECRET: requireKey('JWT_SECRET'),
  NODE_ENV: parsed.NODE_ENV?.trim() || 'production',
  USER_EMAIL: requireKey('USER_EMAIL'),
  USER_PASSWORD: requireKey('USER_PASSWORD'),
  BETTER_AUTH_SECRET: parsed.BETTER_AUTH_SECRET?.trim() || requireKey('JWT_SECRET'),
  GOOGLE_CLIENT_ID: parsed.GOOGLE_CLIENT_ID?.trim() || '',
  GOOGLE_CLIENT_SECRET: parsed.GOOGLE_CLIENT_SECRET?.trim() || '',
};

function formatEnv(vars: Record<string, string>): string {
  return (
    Object.entries(vars)
      .map(([key, value]) => `${key}=${value}`)
      .join('\n') + '\n'
  );
}

type ServiceConfig = {
  filename: string;
  comment: string;
  port: string;
  extra?: Record<string, string>;
};

const services: ServiceConfig[] = [
  {
    filename: '.env.Backend',
    comment: 'Backend Service Environment Variables',
    port: '8000',
    extra: {
      BETTER_AUTH_SECRET: shared.BETTER_AUTH_SECRET,
      GOOGLE_CLIENT_ID: shared.GOOGLE_CLIENT_ID,
      GOOGLE_CLIENT_SECRET: shared.GOOGLE_CLIENT_SECRET,
    },
  },
  {
    filename: '.env.Web',
    comment: 'Web Frontend Service Environment Variables',
    port: '3001',
    extra: {
      BETTER_AUTH_SECRET: shared.BETTER_AUTH_SECRET,
      GOOGLE_CLIENT_ID: shared.GOOGLE_CLIENT_ID,
      GOOGLE_CLIENT_SECRET: shared.GOOGLE_CLIENT_SECRET,
      NEXT_PUBLIC_BACKEND_URL: shared.BACKEND_URL,
    },
  },
  {
    filename: '.env.Engine',
    comment: 'Engine Service Environment Variables',
    port: '8000',
  },
  {
    filename: '.env.DBstorage',
    comment: 'DBstorage Service Environment Variables',
    port: '8000',
  },
  {
    filename: '.env.Snap_Shotting',
    comment: 'Snap Shotting Service Environment Variables',
    port: '8000',
  },
];

mkdirSync(ENV_DIR, { recursive: true });

for (const service of services) {
  const vars: Record<string, string> = {
    DATABASE_URL: shared.DATABASE_URL,
    REDIS_URL: shared.REDIS_URL,
    MONGODB_URL: shared.MONGODB_URL,
    FRONTEND_URL: shared.FRONTEND_URL,
    BACKEND_URL: shared.BACKEND_URL,
    JWT_SECRET: shared.JWT_SECRET,
    PORT: service.port,
    NODE_ENV: shared.NODE_ENV,
    USER_EMAIL: shared.USER_EMAIL,
    USER_PASSWORD: shared.USER_PASSWORD,
    ...service.extra,
  };

  const content = `# ${service.comment}\n# Auto-generated by scripts/sync-docker-env.ts — do not edit manually\n\n${formatEnv(vars)}`;
  const target = path.join(ENV_DIR, service.filename);
  writeFileSync(target, content, 'utf8');
  console.log(`Wrote ${service.filename}`);
}

console.log('\nDocker env files synced from root .env');
